services:
  fairy-api:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["uv", "run", "fastapi", "run", "main_api.py", "--host", "0.0.0.0", "--port", "8000"]
    ports:
      - "8000:8000"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    restart: unless-stopped

  fairy-bot:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["uv", "run", "python", "main_bot.py"]
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
    restart: unless-stopped
    depends_on:
      - fairy-api