apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- backend-api.yaml
- backend-bot.yaml
- frontend.yaml
- mongodb.yaml
images:
- name: ghcr.io/kurazuuuuuu/fairy-backend-bot
  newTag: latest
- name: ghcr.io/kurazuuuuuu/fairy-backend-api
  newTag: latest
- name: ghcr.io/kurazuuuuuu/fairy-frontend
  newTag: 64b6caa35f74d5723ac5b684ed64e7abfde0b64f
