apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- backend-api.yaml
- backend-bot.yaml
- frontend.yaml
- mongodb.yaml
images:
- name: ghcr.io/kurazuuuuuu/fairy-backend-bot
  newTag: d00980ae4102b68f846973acadb5984f94a7eceb
- name: ghcr.io/kurazuuuuuu/fairy-backend-api
  newTag: d00980ae4102b68f846973acadb5984f94a7eceb
- name: ghcr.io/kurazuuuuuu/fairy-frontend
  newTag: 3e141b9c81fffb793990d5f43c6b03a61d89e1ea
